export const API_endpoints = {
  // auth
  loginUser: "/api/login",
  registerUser: "/api/register",
  // countries
  getAllCountries: "/api/countries",
  addCountry: "/api/countries",
  updateCountry: "/api/countries",
  deleteCountry: "/api/countries",
  // states
  getAllStates: "/api/states",
  addState: "/api/states",
  updateState: "/api/states",
  deleteState: "/api/states",
  // districts
  getAllDistricts: "/api/districts",
  addDistrict: "/api/districts",
  updateDistrict: "/api/districts",
  deleteDistrict: "/api/districts",
  // streams
  getAllStreams: "/api/streams",
  addStream: "/api/streams",
  updateStream: "/api/streams",
  deleteStream: "/api/streams",
  // streams
  getAllUniversities: "/api/universities",
  addUniversity: "/api/universities",
  updateUniversity: "/api/universities",
  deleteUniversity: "/api/universities",
  //users
  getUniAdmins: "/api/users/list",
  getHeiAdmins: "/api/users/list",
  getFAAdmins: "/api/users/list",
  // heis
  getAllHeis: "/api/admin/hei",
  addHei: "/api/admin/hei",
  updateHei: "/api/admin/hei",
  deleteHei: "/api/admin/hei",
  // fas
  getAllFAs: "/api/admin/funding-agency",
  addFA: "/api/admin/funding-agency",
  updateFA: "/api/admin/funding-agency",
  deleteFA: "/api/admin/funding-agency",
  // schemes
  getAllSchemes: "/api/schemes",
  addScheme: "/api/schemes",
  // transactions
  getAllTransactions: "/api/transactions",
  addTransaction: "/api/transactions",
  updateTransaction: "/api/transactions",
  deleteTransaction: "/api/transactions",
  // projects
  getAllProjects: "/api/projects",
  addProject: "/api/projects",
  updateProject: "/api/projects",
  deleteProject: "/api/projects",
  // reports
  getAllReports: "/api/reports",
  addReport: "/api/reports",
  updateReport: "/api/reports",
  deleteReport: "/api/reports",
  // phases
  getAllPhases: "/api/phases",
  addPhase: "/api/phases",
  updatePhase: "/api/phases",
  deletePhase: "/api/phases",
};
